apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limit-range
  namespace: default
spec:
  limits:
    - max:
        cpu: 1
      min:
        cpu: 500m
      max:
        memory: 1Gi
      min:
        memory: 500Mi
      type: Pod