version: '3'
services:
  mysql:
    image: mariadb
    container_name: mysql_mariadb
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}" 
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always

  wordpress:
    image: wordpress:php8.0-fpm-alpine
    container_name: wordpress-fpm
    volumes:
      - /data/html:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_ROOT_PASSWORD: "${WORDPRESS_ROOT_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}" 
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}" 
    links:
      - mysql
    restart: always
    expose:
      - 9000
  
  nginx:
    image: nginx:alpine
    container_name: nginx-re
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /data/html:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress    

# volumes:
 # nginx:
  #  driver: 'local'